version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ghcr.io/nestlir/film-react-nest/frontend:latest
    container_name: frontend_film
    networks:
      - webnet
    volumes:
      - frontend_dist:/var/www/frontend  # ✅ Кладем фронт в volume
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ghcr.io/nestlir/film-react-nest/backend:latest
    container_name: backend_film
    networks:
      - webnet
    environment:
      DATABASE_HOST: postgres_film
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 2706
      DATABASE_NAME: film_db
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15
    container_name: postgres_film
    networks:
      - webnet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2706
      POSTGRES_DB: film_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ghcr.io/nestlir/film-react-nest/nginx:latest
    container_name: nginx_film
    networks:
      - webnet
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - frontend_dist:/var/www/frontend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_film
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - webnet
    depends_on:
      - postgres

volumes:
  frontend_dist:
  postgres_data:

networks:
  webnet:
    driver: bridge
