version: "3.8"

services:
  frontend:
    image: ghcr.io/nestlir/film-react-nest/frontend:latest
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped  # Добавляем перезапуск

  backend:
    image: ghcr.io/nestlir/film-react-nest/backend:latest
    env_file:
      - .env
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: film_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped  # Добавляем перезапуск

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped  # Добавляем перезапуск

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: film_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always  # База должна всегда работать
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
